### ISSUE TITLE
[RQ] Protect your API endpoints

### ISSUE THREAD

**Issue by Ronuhz** [FNLookup/fnlookup.github.io#13]
[!] Problems should be described as bugs.

**What feature do you propose?**
Protect your API endpoints

**What would you like to have?**
Your API keys aren't exposed in the dev tool network tab but the fnlookup-api.vercel.app/api is which is no problem. The problem is that I can make a GET request to your custom API and with that I can call the API in your name using up your daily limits and using your paid API key (if you have a paid one)

**Comment by tposejank** [comment]
This has been done
