### ISSUE TITLE
[RQ] Last Updated Shop Sections

### ISSUE THREAD

**Issue by pirica** [FNLookup/fnlookup.github.io#6]
**What feature do you propose?**

Last Updated Shop Sections

- Winter Ski (3x)
- Equip Wraps and Customize Colors! (1x)
- Wraps (2x)
- Featured (2x)
- Daily (1x)
- My Hero Academia (3x)
- MrBeast (2x)
- Survivors In Arms (1x)
- Icons (9x)
- Candywing's Locker (1x)
- 'Tis the Season (4x)

This is released 2h before shop reset.

Official Api (no need Auth)
https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game/shop-sections?lang={language}

```
"_type": "ShopSection",
        "landingPriority": 85,
        "bHidden": false,
        "sectionId": "MrBeast2B",
        "bShowTimer": true,
        "sectionDisplayName": "MrBeast",
        "bShowIneligibleOffers": true
      },
```

Nitestats.com (no need Auth)
https://api.nitestats.com/v1/epic/modes-smart

``` 
"sectionStoreEnds": {
              "MrBeast2B": "2022-12-23T00:00:00Z",
              "HeroAca1B": "2022-12-23T00:00:00Z",
              "HeroAca2B": "2022-12-23T00:00:00Z",
              "HeroAca3B": "2022-12-23T00:00:00Z",
              "Icons5B": "2022-12-23T00:00:00Z",
              "Icons6B": "2022-12-23T00:00:00Z",
              "Icons7B": "2022-12-23T00:00:00Z",
              "Icons8B": "2022-12-23T00:00:00Z",
              "Icons9B": "2022-12-23T00:00:00Z",
              "IconsB": "2022-12-23T00:00:00Z",
              "Icons2B": "2022-12-23T00:00:00Z",
              "Icons3B": "2022-12-23T00:00:00Z",
              "Icons4B": "2022-12-23T00:00:00Z",
              "Featured": "2022-12-23T00:00:00Z",
              "Featured2": "2022-12-23T00:00:00Z",
              "CWingLockerB": "2022-12-23T00:00:00Z",
              "MrBeast1B": "2022-12-23T00:00:00Z",
              "Daily": "2022-12-23T00:00:00Z",
              "SurvivorsInArmsB": "2022-12-23T00:00:00Z",
              "WinterSki": "2022-12-23T00:00:00Z",
              "WinterSki2": "2022-12-23T00:00:00Z",
              "WinterSki3": "2022-12-23T00:00:00Z",
              "Season": "2022-12-23T00:00:00Z",
              "Season2": "2022-12-23T00:00:00Z",
              "Season3": "2022-12-23T00:00:00Z",
              "Season4": "2022-12-23T00:00:00Z",
              "WrapBattle!": "2022-12-23T00:00:00Z",
              "Wraps": "2022-12-23T00:00:00Z",
              "Wraps2": "2022-12-23T00:00:00Z"
```

**What would you like to have?**
Please describe what you expect

**Screenshots or concepts, if possible**
![Screenshot_23](https://user-images.githubusercontent.com/11189930/209134112-8814cecf-366e-45ea-bd68-0a9bb2d8211c.png)

**Comment by tposejank** [comment]
By what I can see, this gives me the rotate out time of a section. Could you please specify more?

**Comment by tposejank** [comment]
Wait I closed this accidentally, my bad

**Comment by pirica** [comment]
> By what I can see, this gives me the rotate out time of a section. Could you please specify more?

This is info is released 2h before shop reset and many people wants to know the upcoming shop.

Yes, but we have 2 endpoints and match both, to get the active ones, dates and translation.

**Comment by tposejank** [comment]
Fortnite content api page is dead :(
