### ISSUE TITLE
[RQ] Batlepass Preview previous seasons+chapters

### ISSUE THREAD

**Issue by pirica** [FNLookup/fnlookup.github.io#8]
**What feature do you propose?**

Would be possible later on to add a menu to choose previous seasons+chapters?

Many Thanks

**Screenshots or concepts, if possible**
[Example Link](https://trackernite.com/battlepass/)

**Comment by tposejank** [comment]
If fortniteapi.io battle pass endpoint supports other seasons parameters, then surely will add.

**Comment by tposejank** [comment]
this has been introduced in v3 on all seasons feature
