### ISSUE TITLE
[RQ] Blog News

### ISSUE THREAD

**Issue by pirica** [FNLookup/fnlookup.github.io#9]
**What feature do you propose?**
Add Blog News

BR Api (no need Auth)
https://www.epicgames.com/fortnite/api/blog/getPosts?category=&postsPerPage=0&offset=0&locale={Language}&rootPageSlug=blog

Competitive Api (no need Auth):
https://www.epicgames.com/fortnite/competitive/api/blog/getPosts?postsPerPage=0&offset=0&locale={Language}&rootPageSlug=news

**Screenshots or concepts, if possible**
![Screenshot_20221223_131532_Chrome](https://user-images.githubusercontent.com/11189930/209342409-20f21490-2e8b-4ce6-934c-4aca380d968e.jpg)

**Comment by tposejank** [comment]
This looks interesting. I will look on it later.

**Comment by pirica** [comment]
Take your time, no rush! Merry Christmas and a happy New Year!

**Comment by tposejank** [comment]
> Take your time, no rush! Merry Christmas and a happy New Year!

So do you!

**Comment by tposejank** [comment]
![image](https://user-images.githubusercontent.com/81495861/210192295-edebb5e0-7436-4d24-8f2c-ff3f203313aa.png)
Unfortunately, this cannot be added to the page. Epic game's api does not allow for other domains to access their API and fetch, so I cannot add this.

**Comment by tposejank** [comment]
Found out about ways to bypass that

**Comment by tposejank** [comment]
Seems like theyre ratelimiting that api. This idk how its gonna go

**Comment by tposejank** [comment]
Couldnt get this working again. Sorry.
